#!/bin/bash

if ! [[ -d "$1" ]] || [[ -z "$2" ]] || ! [[ "$2" == *.gif ]]; then
	echo "Usage: img2gif source_folder destination.gif"
	exit 1
fi

for l in $(cat $1/data.txt)
do
	fps=$l
done

cd $1
files=*.png
sorted_files=""
for l in $files
do
	sorted_files+="$l\n"
done
sorted_files=$(echo -e $sorted_files | sort -n)
convert -delay 1x$fps $sorted_files $2
cd ..

