#!/bin/bash

if ! [[ -f "$1" ]] || [[ -z "$2" ]] || [[ -d "$2" ]]; then
	echo "Usage: video2img source_video new_destination_folder"
	exit 1
fi

fps=$(ffmpeg -i $1 2>&1 | sed -n "s/.*, \(.*\) fp.*/\1/p")
mkdir $2 &>/dev/null
ffmpeg -i $1 -ss 00:30 -t 5 $2/%d.png &>/dev/null

max=1
for f in $2/*.png;do
	n=$(basename ${f%.*})
	if (("$n" > "$max"));then
		max=$n
	fi
done

echo -e "$max\n$fps\n" > $2/data.txt
