#!/bin/bash

#for i in `seq 5`
#do
#	a=$((RANDOM % 100))
#	b=$((RANDOM % 100))
#	c=$((RANDOM % 10))
#	wget http://s3.freefoto.com/images/$a/$b/$a"_"$b"_"$c"_web.jpg"
#done

for a in `seq 31 35`;do
	for b in `seq 10 30`;do
		for c in `seq 30`;do
			wget -nc -q http://s3.freefoto.com/images/$a/$b/$a"_"$b"_"$c"_web.jpg"
		done
	done
done



